export const pages = ['home',
        'about',
        'shop',
        'blog',
        'wishlist',
        'cart',
        'checkout',
        'delivery-information',
        'privacy-policy',
        'contact-us',
        'returns']